services:
  - type: web
    name: cosmic-watch-api
    runtime: docker
    plan: free
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NASA_API_KEY
        sync: false
      - key: FRONTEND_URL
        fromService:
          name: cosmic-watch-ui
          type: static_site
          property: url

  - type: static_site
    name: cosmic-watch-ui
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
